Created CODE_OF_CONDUCT.md
JohnSnowLabs/langtest pull request #863
Opened 2023-10-27 06:08 UTC by RakshitKhajuria

In this PR i added Our CODE_OF_CONDUCT.md file to meet open source Community Standards

2023-10-28 06:26 UTC, chakravarthik27 commented on README.md
In [Contributing](https://github.com/JohnSnowLabs/langtest/tree/RakshitKhajuria-patch-2#contributing) Section:
add links for ideas, discussion, ... etc from the discussion tab as below

![image](https://github.com/JohnSnowLabs/langtest/assets/23481244/a6221f16-f07c-4290-84b5-7357adfbe07a)

2023-10-28 06:31 UTC, chakravarthik27 requested changes
![image](https://github.com/JohnSnowLabs/langtest/assets/23481244/efa2d93c-ff18-46e4-9bb6-594dda1c999d)

Look into the Highlighted one.

2023-11-02 18:01 UTC, ArshaanNazir approved these changes

2023-11-02 18:01 UTC, ArshaanNazir approved these changes

2023-11-03 08:51 UTC, chakravarthik27 approved these changes

2023-11-03 08:56 UTC, merged